name: asset-files
services:
  asset-links:
    image: ghcr.io/sanmerdev/asset-files
    restart: always
    ports:
      - 80:8080
    volumes:
      - asset-data:/app/data
      - ./auth.json:/etc/asset-files/auth.json
volumes:
  asset-data: {}